<?
$aMenuLinks = Array(
    Array(
        "Accueil",
        "/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Tous les produits",
        "catalog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Bestsellers",
        "bestsellers/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Blog",
        "blog/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Contacts",
        "contact/",
        Array(),
        Array(),
        ""
    ),
);
?>